### ISSUE TITLE
Create a description for this app

### ISSUE THREAD

**Issue by jackishere** [unfor19/columbus-app#3]
Need to create a description for this app:
1. How can it help me?
2. Is it possible to add a screenshot?

10x.

**Comment by unfor19** [comment]
@jackishere my friend, you're right, I published it so I can share it with a colleague, so I didn't put an effort in the README :)

I'll add it now, thanks for the interest

**Comment by unfor19** [comment]
Closed in https://github.com/unfor19/columbus-app/commit/3ec34678ed22088e4f99c2b94863367eb36cf1a9
Embarrassed that I haven't initially written something ... Thanks buddy

**Comment by jackishere** [comment]
💜
